export const DEFAULT_PRICE_LIST = [
  { name: "AM, A1", price: "15 500 Kč" },
  { name: "A2", price: "16 500 Kč" },
  { name: "A", price: "16 500 Kč" },
  { name: "B", price: "18 900 Kč" },
  { name: "B expres (do 30 dnů)", price: "28 900 Kč" },
  { name: "B+A2, A", price: "34 500 Kč" },
  { name: "A1/A2+B (jsem držitelem skupiny A1-2 roky)", price: "24 500 Kč" },
  { name: "A1/B+A2 (nejsem držitelem skupiny A1-2 roky)", price: "29 500 Kč" },
  { name: "A1/A2 nebo A2/A (2 roky praxe A1)", price: "5 900 Kč" },
  { name: "A1/A2 nebo A2/A (bez praxe 2 roky)", price: "10 900 Kč" },
  { name: "Kondiční jízdy skupina B – 1 hodina (45 min.)", price: "600 Kč" },
  { name: "Doplňující výcvik skupina B – 1 hodina (45 min.)", price: "500 Kč" },
  { name: "Kondiční jízdy skupina Am, A1, A2, A - 1 hodina (45 min.)", price: "900 Kč" },
  { name: "Přezkoušení z odborné způsobilosti (vrácení ŘP) – sk.B", price: "4 900 Kč" },
  { name: "Přezkoušení z odborné způsobilosti (vrácení ŘP) – sk.B + A", price: "10 500 Kč" },
  { name: "Neomluvená jízda (minimálně 24 hodin předem)", price: "300 Kč" },
  { name: "Storno výcviku (vrácení dokumentace, vyúčtování)", price: "1 000 Kč" },
  { name: "Převod výcviku (administrativa, dokumentace, vyúčtování)", price: "1 000 Kč" },
  { name: "Opravná zkouška jízda", price: "500 Kč" },
  { name: "Nová výuka teorie po třetí neúspěšné zkoušce z předpisů (testy)", price: "1 500 Kč" },
  { name: "Školení začínajících řidičů", price: "6 500 Kč" },
]